sudo: required
services:
  - docker
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE corebos;'
  - mysql -u root --password="" corebos < database/coreBOSTests.sql
  - docker build -t tsolucio/corebos-test -f ./docker/Dockerfile .

script:
  - docker run --network host tsolucio/corebos-test
